structure:
  inline_navbar: true
  inline_pagination: true
  use_decorators: true
  html_mode: default
  use_favicon: true
  show_date: false
style:
  configuration: centered
  width: '960'
  allowCSS: false
  allowJS: false
  stylesheet: sakura-dark-solarized
  include_type: default
  image_cropping: false
  inline_navbar: 1
  customCSS: null
  visually_impared_mode: false
partials:
  header:
    custom_header_image: null
  footer:
    custom_footer_type: markdown
    custom_footer: 'Copyright &copy; 2002-2023 Łukasz Pojezierski'
